site_name: FortiWeb Capture the Flag Workshop
site_description: FortiWeb CTF Workshop docs
site_author: FGallego
site_url: https://f-gallego.github.io/FWB-CTF/
copyright: "40docs Organization"

# Repository
repo_name: F-Gallego/FWB-CTF
repo_url: https://github.com/F-Gallego/FWB-CTF
edit_uri: edit/main/docs/

# Theme configuration
theme:
  name: material
  custom_dir: theme
  logo: fabric-white.svg
  logo_dark: fabric-white.svg
  favicon: favicon.ico
  font:
    text: Inter
    code: Roboto Mono
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
  palette:
    scheme: slate
    primary: black
    accent: indigo

# Markdown extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - glightbox:
      zoomable: true

# Extra CSS and JavaScript
extra_css:
  - extra.css

extra_javascript:
  - custom.js

# Social links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/40docs

not_in_nav: |
  /index.md
